# Generated by Django 5.1 on 2024-08-20 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pool', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pool.categoria'),
        ),
        migrations.AddField(
            model_name='pool',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pool.producto'),
        ),
    ]
