# Generated by Django 5.1 on 2024-08-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='estado',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('listo', 'Listo'), ('en_curso', 'En Curso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='abierto', max_length=20),
        ),
    ]
