# Generated by Django 5.1 on 2024-08-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0003_pool_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='cantidad_disponible',
            new_name='cantidad',
        ),
        migrations.RemoveField(
            model_name='pool',
            name='cantidad_disponible',
        ),
        migrations.RemoveField(
            model_name='pool',
            name='cantidad_minima_participante',
        ),
        migrations.RemoveField(
            model_name='pool',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='pool',
            name='precio',
        ),
        migrations.AddField(
            model_name='pool',
            name='minimo_participantes',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pool',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
