# Generated by Django 5.1 on 2024-09-03 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0004_rename_cantidad_disponible_producto_cantidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='pool',
            name='descripcion',
        ),
    ]
