# Generated by Django 5.1 on 2024-09-03 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0005_remove_categoria_descripcion_remove_pool_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='tipo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('todos', 'Todos')], default='todos', max_length=20),
        ),
    ]
