version: '3.10'

services:
  staging:
    profiles: ["staging"]
    image: poolshop_staging:latest
    container_name: poolshop_staging_container
    restart: unless-stopped
    volumes:
      - ./poolshop:/app
    ports:
      - "8080:8080" 
    env_file:
      - env/stg.env
    environment:
      - DJANGO_SETTINGS_MODULE=poolshop.settings
      - ENVIRONMENT=staging

  production:
    profiles: ["production"]
    image: poolshop_production:latest
    container_name: poolshop_production_container
    restart: unless-stopped
    volumes:
      - ./poolshop:/app
    ports:
      - "8080:8080" 
    env_file:
      - env/prod.env
    environment:
      - DJANGO_SETTINGS_MODULE=poolshop.settings
      - ENVIRONMENT=production