# Generated by Django 5.1 on 2024-09-09 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0007_productoimagen'),
        ('user', '0002_remove_usuario_apellido_remove_usuario_contrasena_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('product_quantity', models.IntegerField()),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pool.pool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'pool')},
            },
        ),
    ]
