name: Deploy Django to GCP with Docker - Staging

on:
  push:
    branches:
      - staging

env:
  ENVIRONMENT: ${{ vars.ENVIRONMENT }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
    
    publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.DOCKER_IMAGE_NAME_STAGING }}:latest \
            --build-arg SECRET_KEY=$SECRET_KEY \
            --build-arg ENVIRONMENT=$ENVIRONMENT \
            --no-cache

      - name: Tag Docker image
        run: docker tag ${{ secrets.DOCKER_IMAGE_NAME_STAGING }}:latest ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME_STAGING }}:latest

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME_STAGING }}:latest
