name: Deploy Django to GCP with Docker - Staging

on:
  push:
    branches:
      - staging

env:
  ENVIRONMENT: ${{ vars.ENVIRONMENT }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
    
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: juancru68
          password: dckr_pat_JNbHNw_bpVEPuS-xAwulzuHO0mA

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build \
            -t poolshop_staging:latest \
            --build-arg ENVIRONMENT=$ENVIRONMENT \
            --no-cache \
            ./backend

      - name: Tag Docker image
        run: docker tag poolshop_staging:latest juancru68/poolshop_staging:latest

      - name: Push Docker image to Docker Hub
        run: docker push juancru68/poolshop_staging:latest

  deploy:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy poolshop-staging \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/poolshop_staging:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --set-env-vars ENVIRONMENT=$ENVIRONMENT
      
      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy poolshop-staging \
            --image docker.io/juancru68/poolshop_staging:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --set-env-vars ENVIRONMENT=$ENVIRONMENT